version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-finder-liferay:
    build:
       context: ./images/finder
    container_name:  §§INSTANCE-finder-liferay
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-lapp-db:finder-db
    ports:
      - "§§PORT1:8080"
    depends_on:
      - §§INSTANCE-finder-liferay
      - §§INSTANCE-app-data
    volumes_from: 
      - §§INSTANCE-app-data

§§INSTANCE-finder-db:
  image: postgres:9.5
  container_name:  §§INSTANCE-finder-db
  restart: unless-stopped
  environment:
      - POSTGRES_PASSWORD=8$AGb3iüe!j-gLr+U]6nDZA9actXuL
      - POSTGRES_USER=liferay
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=lportal
  networks:
    - bibbox-default-network
  depends_on:
    - §§INSTANCE-app-data
  volumes_from: 
    - §§INSTANCE-app-data

  §§INSTANCE-app-data:
    image: busybox
    container_name: §§INSTANCE-app-data
    networks:
      - bibbox-default-network
    volumes:
      - ./data/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
      - ./data/opt/liferay:/opt/liferay
      - ./data/init.d/liferay:/etc/init.d/liferay
      - ./data/init.d/functions:/etc/init.d/functions
      - ./data/db_backup_20180817.sql:/docker-entrypoint-initdb.d/db_backup_20180817.sql